FROM almalinux:8 
RUN useradd nishal
USER nishal 
RUN echo "Helo Docker container" > /tmp/hello.txt

#in this user parameter what we are doing is we are restricting the user
#to direct login with root account instead he need to login with his user account for more security
